version: "3"

services:

  elasticsearch:
    image: elasticsearch:6.5.0
    ports: 
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  kibana:
    image: kibana:6.6.1
    ports:
    - "5601:5601"
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yaml:ro
  logstash:
    image: logstash
    links:
    - elasticsearch
    volumes:
    - ./:/config-dir
# - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    command: logstash -f /config-dir/logstash.conf
    depends_on:
    - elasticsearch
