version: "3"

services:

  elasticsearch:
    image: elasticsearch:6.6.2
    container_name: es
    environment: 
#    - discovery.type=single-node
    - xpack.security.enabled=false
    ports: 
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  kibana:
    image: kibana:6.6.2
    container_name: kiba
    ports:
    - "5601:5601"
    links:
    - elasticsearch
    depends_on:
    - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
