version: '3'
services:

  kafka-cluster:
    image: landoop/fast-data-dev
    container_name: kafka
    environment:
      - DISABLE=azure-documentdb,blockchain,bloomberg,coap,druid,ftp,hazelcast,influxdb,jms,kudu,mqtt,rethink,voltdb,yahoo
      - RUNTESTS=0
    ports:
      - 2181:2181           # Zookeeper
      - 3030:3030           # Landoop UI
      - 8081-8083:8081-8083 # REST Proxy, Schema Registry, Kafka Connector
      - 9092:9092           # Kafka Broker

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-cluster:9092"
      SCHEMAREGISTRY_CONNECT: "kafka-cluster:8082"
    depends_on:
      - "kafka-cluster"

  kafka_manager:
    image: hlebalbau/kafka-manager:2.0.0.2
    container_name: kafka-manager
    ports:
      - 9001:9000
    environment:
      ZK_HOSTS: 'kafka-cluster:2181'
      APPLICATION_SECRET: "MySecret"
    command: -Dpidfile.path=/dev/null
    depends_on:
      - "kafka-cluster"
