version: "3"
services:
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes: 
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
