version: "3"
services:
  pg:
    image: postgres:9.5-alpine
    container_name: pg
    hostname: pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'db1'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'

  pga:
    image: dpage/pgadmin4:latest
    container_name: pga
    hostname: pga
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@void.io
      PGADMIN_DEFAULT_PASSWORD: admin
